### ISSUE TITLE
Question about submission of experiments

### ISSUE THREAD

**Issue by hanros1994** [MonroeQuantumNetworks/artiq-experiments#3]
Hi

Thank you for uploading your ARTIQ code. I wanted to ask about the submission of experiments.  how are you submitting the sequence of experiments in the repository, do you have a single execution script to submit all the experiments in an order? could you please provide some more information on your submission process. I would really appreciate your advice.

**Comment by georgetoh** [comment]
Hi hanros1994, we actually keep our process very simple and run one experiment at a time. We use the "settings" script to toggle lasers on and off. To run an experiment, we choose the relevant script and run that. Sometimes we might queue up multiple instances of the same experiment to run several times in a row.

What kind of experimental setup have you got? Do you need to run complicated multi-script experiments?

**Comment by hanros1994** [comment]
> Hi hanros1994, we actually keep our process very simple and run one experiment at a time. We use the "settings" script to toggle lasers on and off. To run an experiment, we choose the relevant script and run that. Sometimes we might queue up multiple instances of the same experiment to run several times in a row.
> 
> What kind of experimental setup have you got? Do you need to run complicated multi-script experiments?

Hi George 

Thanks alot for the reply. I am actually in the same boat as you, I don't need to run complicated multi-script experiments rather several different experiments in an sequence. The way I approached this was to try to run an 'master' experiment which would references all the other experiments so essentially running an experiment from another experiment. For example in this 'master' experiment I would be able to set the arguments for all the respective experiments, comment out the submission for a particular experiment in the sequence if needed and then also repeat the submission of experiments using a for loop so that the sequence repeat a desired number of times. This probably makes more sense if you look at the code I have produced attached below. The reason I have gone with this approach is because I can set all he required arguments and repetitions for the entire script in a single file - this 'master' experiment. Unfortunately this code is not submitting any experiment which I have checked from artiq_client show schedule and the master log. Submitting the individual files using the artiq_dashboard or using artiq_client submit does work so I don't know where the issue is with my code. Can you spot what the issue may be with my code, is it an issue with expid? I would really appreciate your help.

`
from artiq.experiment import *
from artiq.coredevice import ad9910
import numpy as np
from artiq.master.worker_db import DeviceManager
from artiq.master.databases import DeviceDB
import artiq.frontend.artiq_run



#ddb = DeviceDB("device_db.py")
#devmgr = DeviceManager(ddb)

#create a scheduler 

class Scheduling_experiments(EnvExperiment):
    
    
    def build(self):
        self.setattr_device("core") 
        self.setattr_device("scheduler")
        
        
    
    def run(self):
        expid_1 = {
            "file": "repository/urukul_single_tone_1.py",
            "class_name": "Urukul_Frequency_Pulse",
            # "arguements": {"freq = 100*MHz"}
            # "log_level": self.scheduler.expid["l"],
            # "repo_rev": self.scheduler.expid["repo_rev"],
            }
        
        expid_2 = {
            "file": "repository/urukul_single_tone_2.py",
            "class_name": "Urukul_Frequency_Pulse_2",
            # "arguements": {"freq = 500*MHz"}
            # "log_level": self.scheduler.expid["log_level"],
            # "repo_rev": self.scheduler.expid["repo_rev"],
            }

        self.scheduler.submit("main", expid_1)
        # delay(10*s)
        #self._scheduler.submit("main", expid_2)
        
        print ("current schedule")`

**Comment by drewrisinger** [comment]
@hanros1994 GitHub issues for unrelated projects are generally not the place to look for support of the kind you're looking for. The M-Labs forums are more suited for this. I replied to your thread there.
