### ISSUE TITLE
ARTIQ 6 transition

### ISSUE THREAD

**Issue by lriesebos** [MonroeQuantumNetworks/artiq-experiments#4]
We will move the ionphoton system to ARTIQ 6. @georgetoh @igoetting

# Preparations before transition

1. Install linux and ARTIQ on the new computer that is available for ARTIQ 6. There is a new SSD available in that machine that can be used. Just remove the old SSD. Probably ubuntu 22.04.
2. Install nix, artiq, and other software required
3. keep existing network registrations but potentially modify subnet address

# Transition "week"

1. Confirm that we can flash existing ARTIQ 5 gateware using the existing computers such that we can revert the system if needed. This can initially be tested using a spare kasli 1.1, and should then be tested on the ionphoton kasli to verify that the flashed gateware works with the existing software. We can also check the bootloader messages to see if the gateware matches existing gateware and see if things like the idle kernel work correctly.
1. now flash the latest ARTIQ 6 gateware on the kasli and test if the existing software works on ARTIQ 6.
2. run experiments and see if any timing errors occur. fix bugs where needed.
1. make some low-hanging code improvements if necessary. including startup and idle kernels.

# Gitlab transition

we probabaly want to transition the repo with history, but if not, then we can save a lot of space and only transfer files that are relevant. because the repo currently includes a 800 MB of hdf5 files too.

1. transition the whole repo with history to gitlab and make a pre-transition tag
2. probably do a bit of cleanup to delete files that shouldn't be there
3. update gitignore

**Comment by drewrisinger** [comment]
If transitioning the repo as-is, ``git filter-repo`` might be a good/helpful option for reducing repo size due to files that shouldn't be in-tree. https://github.com/newren/git-filter-repo. Available via Nix.

**Comment by lriesebos** [comment]
issue moved to https://gitlab.com/duke-artiq/ion-photon/-/issues/3
